支持嵌套无边框组件
wangwenx190/framelesshelper pull request #190
Opened 2022-12-08 02:27 UTC by 1bbb

2022-12-08 02:29 UTC, wangwenx190 commented
感谢！但FramelessMainWindow这个类好像被遗漏了

2022-12-08 02:35 UTC, 1bbb commented
> FramelessMainWindow

貌似没有这种使用场景。嵌套最小化之后
![image](https://user-images.githubusercontent.com/3361974/206342410-a5437b33-c2a5-4d75-ba04-abf797c046da.png)
标题栏貌似是windows自带的

2022-12-08 02:50 UTC, wangwenx190 commented
好的，我这边需要验证下。

2022-12-08 02:50 UTC, wangwenx190 commented
使用过程中有发现别的问题吗？

2022-12-08 02:53 UTC, 1bbb commented
> 使用过程中有发现别的问题吗？

有的，如果嵌套三层，关闭第二层的时候，会导致主窗体躲到其他应用的后面（不是最小化）。这个我还在验证。

2022-12-08 02:57 UTC, wangwenx190 commented
FramelessHelper目前的设计是，每个顶层窗口都对应一个无边框窗口，所以理论上不能嵌套（因为子窗口的顶层窗口和父窗口的顶层窗口是同一个，比如QtQuick）。你这个PR应该是能区分开嵌套窗口的顶层窗口，所以实现了嵌套，但由于FramelessHelper最初就没有考虑过这种情况，所以可能会有bug。

2022-12-08 02:58 UTC, wangwenx190 commented
如果不嵌套的话，有发现什么问题吗？

2022-12-08 03:00 UTC, 1bbb commented
> 如果不嵌套的话，有发现什么问题吗？

我在win10和win7测试过，貌似没啥问题。麻烦你帮忙验证下。

2022-12-08 03:01 UTC, wangwenx190 commented
> > 如果不嵌套的话，有发现什么问题吗？
> 
> 我在win10和win7测试过，貌似没啥问题。麻烦你帮忙验证下。

不嵌套的情况我自己也测试了好多了，至少发现的问题都已经解决了。你说的验证是指验证这个PR吗？

2022-12-08 03:03 UTC, 1bbb commented
> > > 如果不嵌套的话，有发现什么问题吗？
> > 
> > 
> > 我在win10和win7测试过，貌似没啥问题。麻烦你帮忙验证下。
> 
> 不嵌套的情况我自己也测试了好多了，至少发现的问题都已经解决了。你说的验证是指验证这个PR吗？
是的，比如在linux和mac上，我目前还无法验证。或者其他版本的Qt，我使用的5.12.7的Qt

2022-12-08 03:08 UTC, wangwenx190 commented
> 嗯，win11我也测试过

好的。

2022-12-08 03:24 UTC, wangwenx190 commented on src/widgets/framelesswidget.cpp
> +    : QWidget(parent, Qt::Window)
请问这个Qt::Window是只有FramelessWidget需要吗？如果不加的话你那边是什么现象呢？

2022-12-08 03:24 UTC, wangwenx190 commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
这个是否要像下面一样改成指针？

2022-12-08 03:49 UTC, 1bbb commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
> 这个是否要像下面一样改成指针？

exec是阻塞的

2022-12-08 07:34 UTC, 1bbb commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
可以让无边框的组件的背景色不跟随系统主题变化吗？

2022-12-08 07:38 UTC, wangwenx190 commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
窗口背景色还是标题栏背景色？

2022-12-08 07:41 UTC, 1bbb commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
窗口

2022-12-08 07:44 UTC, wangwenx190 commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
窗口的话你把blurBehindWindow关了就可以了，这个是模拟亚克力效果的。demo默认都全局开启了，代码在main.cpp里。如果你用的是这个库提供的标题栏的话，可以通过ChromePalette这个类来修改颜色，如果你用的是你自己的标题栏就无所谓了。

2022-12-08 07:46 UTC, 1bbb commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
> 窗口的话你把blurBehindWindow关了就可以了，这个是模拟亚克力效果的。demo默认都全局开启了，代码在main.cpp里。如果你用的是这个库提供的标题栏的话，可以通过ChromePalette这个类来修改颜色，如果你用的是你自己的标题栏就无所谓了。
>好的，谢谢。

2022-12-08 07:46 UTC, 1bbb commented on examples/mainwindow/mainwindow.cpp
> +        Dialog dlg(this);
好的，谢谢

2022-12-08 08:17 UTC, wangwenx190 commented on src/widgets/framelesswidgetshelper.cpp
> +   /* QWidget * const topLevelWindow = (window->nativeParentWidget()
是所有涉及nativeParentWidget的地方都要修改吗

2022-12-08 08:37 UTC, wangwenx190 requested changes

2022-12-08 08:37 UTC, wangwenx190 commented on examples/mainwindow/mainwindow.cpp
> +    connect(m_mainWindow->pushButton, &QPushButton::clicked, [this]{
这个要加第三个参数，要改成：
`connect(m_mainWindow->pushButton, &QPushButton::clicked, this, [this](){`

2022-12-08 08:37 UTC, wangwenx190 commented on examples/mainwindow/mainwindow.cpp
> +        auto* wgt = new Widget(this);
这里也改成widget比较好

2022-12-08 08:57 UTC, wangwenx190 commented on examples/mainwindow/mainwindow.cpp
> +    connect(m_mainWindow->pushButton_2, &QPushButton::clicked, [this]{
刚才忘记这里了，也需要加第三个参数

2022-12-09 01:10 UTC, 1bbb commented on examples/mainwindow/mainwindow.cpp
> +    connect(m_mainWindow->pushButton, &QPushButton::clicked, [this]{
都是主线程调用，不走队列，this可以不加，当然加了也行

2022-12-09 01:45 UTC, wangwenx190 commented on examples/mainwindow/mainwindow.cpp
> +    connect(m_mainWindow->pushButton, &QPushButton::clicked, [this]{
推荐做法是能加的都加

2022-12-09 01:47 UTC, wangwenx190 commented on src/widgets/framelesswidget.cpp
> +    : QWidget(parent, Qt::Window)
我感觉不止FramelessWidget需要这个，如果你要嵌套FramelessMainWindow或者FramelessDialog，他们也需要设置window flag

2022-12-09 06:11 UTC, 1bbb commented
> FramelessHelper目前的设计是，每个顶层窗口都对应一个无边框窗口，所以理论上不能嵌套（因为子窗口的顶层窗口和父窗口的顶层窗口是同一个，比如QtQuick）。你这个PR应该是能区分开嵌套窗口的顶层窗口，所以实现了嵌套，但由于FramelessHelper最初就没有考虑过这种情况，所以可能会有bug。

无边框MainWindow 嵌套 无边框Dialog1（模态） 再嵌套一层无边框组件（widget或者Dialog）。最后关闭Dialog1的时候，MainWindow会躲到其他应用程序后面。目前我还没到是啥原因。我在项目中用了一个非友好的的方式如下图：
![image](https://user-images.githubusercontent.com/3361974/206636520-88a70b05-f33b-4aac-a718-22716c5e460d.png)

2022-12-09 08:49 UTC, 1bbb commented
> FramelessHelper目前的设计是，每个顶层窗口都对应一个无边框窗口，所以理论上不能嵌套（因为子窗口的顶层窗口和父窗口的顶层窗口是同一个，比如QtQuick）。你这个PR应该是能区分开嵌套窗口的顶层窗口，所以实现了嵌套，但由于FramelessHelper最初就没有考虑过这种情况，所以可能会有bug。

![image](https://user-images.githubusercontent.com/3361974/206662233-bd8fcd28-f752-47ce-beea-2a16ed50f591.png)
注释了这行代码，问题解决了

2022-12-09 08:50 UTC, wangwenx190 commented
> 注释了这行代码，问题解决了

是指那个窗口会跑到底下的问题吗

2022-12-09 08:53 UTC, 1bbb commented
> 



> > 注释了这行代码，问题解决了
> 
> 是指那个窗口会跑到底下的问题吗

是的
![image](https://user-images.githubusercontent.com/3361974/206663069-1fd56fc9-7cb9-4ecd-8295-3e2cb9679efa.png)
关闭2的时候 1会跑到其他应用程序后面

2022-12-09 08:54 UTC, 1bbb commented
> > 注释了这行代码，问题解决了
> 
> 是指那个窗口会跑到底下的问题吗

是的 关闭2的时候，1会跑到其他程序后面
![image](https://user-images.githubusercontent.com/3361974/206663244-2b25767f-85fb-4274-85bc-b97dbed355b0.png)

2022-12-09 08:57 UTC, wangwenx190 commented
很怪啊，那个函数只有窗口初始化的时候才会调用一次，怎么会出现其他窗口关闭反而影响当前窗口的事情呢

2022-12-09 08:57 UTC, wangwenx190 commented
不过注释掉问题也不大，那个函数没有执行关键代码

2022-12-09 08:57 UTC, 1bbb commented
> 很怪啊，那个函数只有窗口初始化的时候才会调用一次，怎么会出现其他窗口关闭反而影响当前窗口的事情呢

还没细看，可能是触发了什么事件

2022-12-09 08:59 UTC, wangwenx190 commented
> 还没细看，可能是触发了什么事件

没事，不是什么重要问题。不过如果你要注释掉这个函数的话，还有其他的地方要修改

2022-12-09 09:00 UTC, wangwenx190 commented
https://github.com/wangwenx190/framelesshelper/blob/main/src/widgets/widgetssharedhelper.cpp#L198-L207

2022-12-09 09:01 UTC, wangwenx190 commented
https://github.com/wangwenx190/framelesshelper/blob/main/src/quick/framelessquickhelper.cpp#L659-L684

这一段可以整个去掉

2022-12-09 09:05 UTC, 1bbb commented
> > 还没细看，可能是触发了什么事件
> 
> 没事，不是什么重要问题。不过如果你要注释掉这个函数的话，还有其他的地方要修改

目前仅在windows，Qt5.12.7上测试。其他的可能需要帮忙验证

2022-12-09 09:12 UTC, wangwenx190 commented
> 目前仅在windows，Qt5.12.7上测试。其他的可能需要帮忙验证

如果你单纯指注释掉那个函数的话，我比较清楚那个函数的目的及作用，所以Windows平台是没问题的，其他平台的代码也不一样，也无需验证。

如果你是指你这整个PR的话，我周末在我的mac设备上验证下。

2022-12-09 09:16 UTC, 1bbb commented
> > 目前仅在windows，Qt5.12.7上测试。其他的可能需要帮忙验证
> 
> 如果你单纯指注释掉那个函数的话，我比较清楚那个函数的目的及作用，所以Windows平台是没问题的，其他平台的代码也不一样，也无需验证。
> 如果你是指你这整个PR的话，我周末在我的mac设备上验证下。

好的 那你看这个注释的这个函数需要提交pr吗？

2022-12-09 09:18 UTC, wangwenx190 commented
> 那你看这个注释的这个函数需要提交pr吗？

可以的，不过要把下面这两个地方一起去掉

https://github.com/wangwenx190/framelesshelper/blob/main/src/widgets/widgetssharedhelper.cpp#L198-L207

https://github.com/wangwenx190/framelesshelper/blob/main/src/quick/framelessquickhelper.cpp#L659-L684

2022-12-09 09:20 UTC, 1bbb commented on src/widgets/framelesswidgetshelper.cpp
> +   /* QWidget * const topLevelWindow = (window->nativeParentWidget()
> 是所有涉及nativeParentWidget的地方都要修改吗

应该是的，因为nativeparentwidget和window。如果是嵌套的情况下，意义完全不一样，一个是自己，一个是父节点

2022-12-09 09:21 UTC, 1bbb commented
> > 那你看这个注释的这个函数需要提交pr吗？
> 
> 可以的，不过要把下面这两个地方一起去掉
> 
> https://github.com/wangwenx190/framelesshelper/blob/main/src/widgets/widgetssharedhelper.cpp#L198-L207
> 
> https://github.com/wangwenx190/framelesshelper/blob/main/src/quick/framelessquickhelper.cpp#L659-L684

get

2022-12-09 09:22 UTC, 1bbb commented
get

2022-12-09 09:22 UTC, wangwenx190 commented on src/widgets/framelesswidgetshelper.cpp
> +   /* QWidget * const topLevelWindow = (window->nativeParentWidget()
这个地方还是加一句注释吧，稍微解释一下为什么不能用nativeParentWidget这个函数

2022-12-09 10:06 UTC, 1bbb commented on src/widgets/framelesswidgetshelper.cpp
> +   /* QWidget * const topLevelWindow = (window->nativeParentWidget()
> 这样的话麻烦你把StandardTitleBar里的nativeParentWidget也修改一下吧，估计也有问题

titlebar应该是无问题的，因为他本身不可能是个window，只能是父节点才可能是window

2022-12-10 04:15 UTC, wangwenx190 requested changes

2022-12-10 04:15 UTC, wangwenx190 commented on include/FramelessHelper/Quick/private/framelessquickhelper_p.h
> +   // Q_NODISCARD bool eventFilter(QObject *object, QEvent *event) override;
直接删掉就行，不用注释

2022-12-10 04:15 UTC, wangwenx190 commented on src/core/framelesshelper_win.cpp
> +    /*
直接删掉，不用注释

2022-12-10 04:15 UTC, wangwenx190 commented on src/quick/framelessquickhelper.cpp
> +/*
直接删掉

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/framelessdialog.cpp
> +    setAttribute(Qt::WA_NativeWindow);
这个可以挪到FramelessDialogPrivate的initialize函数中，只要在FramelessWidgetsHelper::get之前执行就可以了

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/framelessdialog.cpp
> +    d_ptr.reset(new FramelessDialogPrivate(this));
按上面那样修改后，此处也不需要了，可以还原到原本的代码

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/framelessmainwindow.cpp
> +    setAttribute(Qt::WA_NativeWindow);
同上

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/framelesswidget.cpp
> +    setAttribute(Qt::WA_NativeWindow);
同上

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/framelesswidgetshelper.cpp
> +   /* QWidget * const topLevelWindow = (window->nativeParentWidget()
不用注释了，还是直接删掉吧

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/framelesswidgetshelper.cpp
> +        /*if (QWidget * const nativeParent = widget->nativeParentWidget()) {
直接删掉

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/framelesswidgetshelper.cpp
> +           /*
直接删掉

2022-12-10 04:15 UTC, wangwenx190 commented on src/widgets/widgetssharedhelper.cpp
> +/*
直接删掉

2022-12-10 04:15 UTC, wangwenx190 commented
https://github.com/wangwenx190/framelesshelper/blob/main/src/quick/framelessquickhelper.cpp#L189

https://github.com/wangwenx190/framelesshelper/blob/main/src/quick/framelessquickhelper.cpp#L263

这两个地方也可以删掉了

2022-12-10 08:42 UTC, wangwenx190 commented
现在已经修改完毕了吗？还是还有地方要修改？

2022-12-12 01:07 UTC, wangwenx190 commented
你还要继续修改吗？我打算差不多就合入了

2022-12-12 05:05 UTC, 1bbb commented
> 你还要继续修改吗？我打算差不多就合入了

弹出的位置 感觉有点问题

2022-12-12 05:09 UTC, wangwenx190 commented
> > 你还要继续修改吗？我打算差不多就合入了
> 
> 弹出的位置 感觉有点问题

因为demo代码中指定了窗口的位置，你注释掉看看呢

2022-12-12 05:13 UTC, wangwenx190 commented
看出来了，确实有点问题。但我前几天测你这个PR的时候没遇到这个问题。你是又改了什么吗？

2022-12-12 05:21 UTC, 1bbb commented
> 看出来了，确实有点问题。但我前几天测你这个PR的时候没遇到这个问题。你是又改了什么吗？

我把移动位置代码注释了，就是这样的

2022-12-12 06:00 UTC, wangwenx190 commented
没事，这个问题不大的。可以留着以后解决。

2022-12-12 06:04 UTC, 1bbb commented
> 没事，这个问题不大的。可以留着以后解决。

主要是redy中移动，不是很友好

2022-12-12 06:10 UTC, wangwenx190 commented
> > 没事，这个问题不大的。可以留着以后解决。
> 
> 主要是redy中移动，不是很友好

这个不太好解决，因为在ready信号发出之前，Qt的platform window尚未完成初始化，如果你这时候修改了窗口的位置和尺寸，那么等platform window初始化完成之后，窗口的位置和大小会再次发生变化，所以也不友好。当然这个也不是一定的，有时候初始化很快，那么你不等待ready也没问题。

2022-12-12 08:19 UTC, 1bbb commented
> > > 没事，这个问题不大的。可以留着以后解决。
> > 
> > 
> > 主要是redy中移动，不是很友好
> 
> 这个不太好解决，因为在ready信号发出之前，Qt的platform window尚未完成初始化，如果你这时候修改了窗口的位置和尺寸，那么等platform window初始化完成之后，窗口的位置和大小会再次发生变化，所以也不友好。当然这个也不是一定的，有时候初始化很快，那么你不等待ready也没问题。

问题找到了但是不知道怎么修改。如果是嵌套的时候是需要保存下，window的parentWindow，window确定位置的时候，应该使用parentWindow而不是window。
![image](https://user-images.githubusercontent.com/3361974/206995393-5f2d1381-2b79-4415-bfeb-e807310d11fe.png)

2022-12-12 08:23 UTC, 1bbb commented
> > > > > 没事，这个问题不大的。可以留着以后解决。
> > > > 
> > > > 
> > > > 主要是redy中移动，不是很友好
> > > 
> > > 
> > > 这个不太好解决，因为在ready信号发出之前，Qt的platform window尚未完成初始化，如果你这时候修改了窗口的位置和尺寸，那么等platform window初始化完成之后，窗口的位置和大小会再次发生变化，所以也不友好。当然这个也不是一定的，有时候初始化很快，那么你不等待ready也没问题。
> > 
> > 
> > 问题找到了但是不知道怎么修改。如果是嵌套的时候是需要保存下，window的parentWindow。window确定位置的时候，应该使用parentWindow而不是window。 ![image](https://user-images.githubusercontent.com/3361974/206995393-5f2d1381-2b79-4415-bfeb-e807310d11fe.png)
> 
> 针对的是哪个问题？窗口位置不对的问题吗？

是的 就是那个位置不对的问题。基于window去定位的代码在哪儿？

2022-12-12 08:28 UTC, wangwenx190 commented
其他地方就没有动窗口位置的了

2022-12-12 08:33 UTC, 1bbb commented
> https://github.com/wangwenx190/framelesshelper/blob/main/src/widgets/framelesswidgetshelper.cpp#L495
> 
> 这里也有

这边貌似都没走到，你的方法我试过了，貌似不工作，很是奇怪

2022-12-12 08:34 UTC, wangwenx190 commented
其他地方也没有去修改窗口的位置和大小了，要不就是QPA的行为，这个就和FramelessHelper没关系了，而且FramelessHelper也控制不了

2022-12-12 08:41 UTC, 1bbb commented
> 其他地方也没有去修改窗口的位置和大小了，要不就是QPA的行为，这个就和FramelessHelper没关系了，而且FramelessHelper也控制不了

我确信就是这个window的问题，这个代码注释了，位置就正确了。此时window和parentwindow是同一个
![image](https://user-images.githubusercontent.com/3361974/206999732-74ee08ab-ab27-4ea9-a23f-788255d81281.png)

2022-12-12 08:54 UTC, wangwenx190 commented
这个问题不好找原因，可以先搁置，留待下一个PR解决。这个PR主要是为了解决不能嵌套窗口的问题，也不要整合太多其他的东西。

2022-12-14 01:10 UTC, 1bbb commented
> 这个问题不好找原因，可以先搁置，留待下一个PR解决。这个PR主要是为了解决不能嵌套窗口的问题，也不要整合太多其他的东西。

确实不好找原因，我尝试了下，目前还没找到原因

2022-12-14 05:10 UTC, wangwenx190 commented
> > 这个问题不好找原因，可以先搁置，留待下一个PR解决。这个PR主要是为了解决不能嵌套窗口的问题，也不要整合太多其他的东西。
> 
> 确实不好找原因，我尝试了下，目前还没找到原因

是的，这个问题留待以后解决吧，也不是什么严重的问题。把我前面提到的地方稍微改下吧，我准备merge了。

2022-12-14 15:45 UTC, 1bbb commented
> > 这个问题不好找原因，可以先搁置，留待下一个PR解决。这个PR主要是为了解决不能嵌套窗口的问题，也不要整合太多其他的东西。
> 
> 确实不好找原因，我尝试了下，目前还没找到原因

我发现了个问题，只要插入windowId之后，获取的位置就不对了。我返回nullptr，位置就是对的。实在没看出来，windowId是怎么影响位置的。
![image](https://user-images.githubusercontent.com/3361974/207641229-98544ced-f89e-4cce-a147-9e63448d97c2.png)

2022-12-14 15:46 UTC, 1bbb commented
> > > 这个问题不好找原因，可以先搁置，留待下一个PR解决。这个PR主要是为了解决不能嵌套窗口的问题，也不要整合太多其他的东西。
> > 
> > 
> > 确实不好找原因，我尝试了下，目前还没找到原因
> 
> 是的，这个问题留待以后解决吧，也不是什么严重的问题。把我前面提到的地方稍微改下吧，我准备merge了。

对于嵌套无边影响还是蛮大的，偏移比较大，甚至出屏了。你提到的问题，我已经改了。

2022-12-15 02:34 UTC, wangwenx190 commented
> 对于嵌套无边影响还是蛮大的，偏移比较大，甚至出屏了

主要是这个问题容易规避，可以在创建窗口后手动调整窗口位置

2022-12-15 02:37 UTC, wangwenx190 commented
> 我发现了个问题，只要插入windowId之后，获取的位置就不对了。我返回nullptr，位置就是对的。实在没看出来，windowId是怎么影响位置的。

插入windowId后，后续的操作都是经过FramelessWidgetsHelper了，可能那里的代码还是有点问题的

2022-12-15 02:39 UTC, wangwenx190 commented
> 你提到的问题，我已经改了。

那你暂时不要提交新代码了，我这边调整一下就合入

2022-12-15 02:55 UTC, 1bbb commented
> > 我发现了个问题，只要插入windowId之后，获取的位置就不对了。我返回nullptr，位置就是对的。实在没看出来，windowId是怎么影响位置的。
> 
> 插入windowId后，后续的操作都是经过FramelessWidgetsHelper了，可能那里的代码还是有点问题的

我在这里return，FramelessWidgetsHelper 应该管理不到了吧？
![image](https://user-images.githubusercontent.com/3361974/207761324-e32b7a72-c949-432c-b6e2-b1b41bf85b41.png)

2022-12-15 02:57 UTC, wangwenx190 commented
> 我在这里return，FramelessWidgetsHelper 应该管理不到了吧？

是。不过这个PR你先不要动了。你要再调整的话就换个分支，不要影响到这个PR。

2022-12-15 03:00 UTC, 1bbb commented
> > 我在这里return，FramelessWidgetsHelper 应该管理不到了吧？
> 
> 是。不过这个PR你先不要动了。你要再调整的话就换个分支，不要影响到这个PR。

嗯 暂时没提交

2022-12-15 03:35 UTC, wangwenx190 commented
已经合入主线

2022-12-15 03:35 UTC, closed without merging

2022-12-15 08:00 UTC, wangwenx190 commented
在Deepin 20.8上测过了，没什么问题。macOS大概率也是没问题的。最需要测试的是Windows平台，因为说实话只有Windows平台不支持嵌套。