fix qmake linux build, and fix the "Quick" example
wangwenx190/framelesshelper pull request #194
Opened 2022-12-20 13:36 UTC by micpub

2022-12-21 02:31 UTC, wangwenx190 requested changes

2022-12-21 02:31 UTC, wangwenx190 commented on examples/quick/ApplicationWindow.qml
> +    Connections {
Why is this change necessary?

2022-12-21 02:31 UTC, wangwenx190 commented on qmake/core.pri
> +    PKGCONFIG += gtk+-3.0 xcb
Please remove "xcb", it's now not required anymore.

2022-12-21 12:07 UTC, wangwenx190 commented
OK, thanks! But I still want to know why you change the QtQuick demo.

2022-12-21 12:47 UTC, micpub commented
i've wrote about it above but let me write it again:

example does not start - on console this can be read: 
`
<WARNING> QQmlApplicationEngine failed to load component
<WARNING> qrc:/Demo/HomePage.qml:28:5: Type Window unavailable
<WARNING> qrc:/Demo/Window.qml:46:5: "FramelessWindow.onClosing" is not available in org.wangwenx190.FramelessHelper 1.0.
<CRITICAL> The QML engine failed to create component: QUrl("qrc:/Demo/HomePage.qml")
`
using Connections element the example doest start-up correctly and works as it should.

2022-12-23 01:45 UTC, wangwenx190 commented
Could you try to add the following line below the referred line to see if the workaround can be removed?

```cpp
qmlRegisterRevision<QWindow, 254>(QUICK_URI_FULL);
```

https://github.com/wangwenx190/framelesshelper/blob/main/src/quick/framelessquickmodule.cpp#L103

2022-12-29 14:30 UTC, micpub commented
it doesnt help at all, still gives error:

`qrc:/Demo/Window.qml:46:5: "FramelessWindow.onClosing" is not available in org.wangwenx190.FramelessHelper 1.0.`

2022-12-30 02:35 UTC, wangwenx190 commented
OK, thanks for your PR!

2022-12-30 02:35 UTC, merged