Add Universal build for macOS.
wangwenx190/framelesshelper pull request #217
Opened 2023-05-17 07:35 UTC by mentalfl0w

2023-05-17 07:46 UTC, wangwenx190 commented
你实际编译过吗？编译正常吗

2023-05-17 08:13 UTC, mentalfl0w commented
> 你实际编译过吗？编译正常吗

是的，编译正常，输出的库架构也正常。
<img width="968" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/a12d248c-dab1-4da4-ae64-141117ea64b0">
<img width="566" alt="image" src="https://github.com/wangwenx190/framelesshelper/assets/30333935/fc29f6c6-09a2-4a0d-9e28-27d02d5e145e">

2023-05-17 08:16 UTC, wangwenx190 commented
不过你不是可以直接在config的时候设置`CMAKE_OSX_ARCHITECTURES `吗？为什么要单独写到CMakeList里

2023-05-17 08:23 UTC, mentalfl0w commented
打算将FramelessHelper作为子模块使用，但好像如果不在CMakeList里面配置这个的话，最后编译出来的lib并不包含两个架构，只包含编译平台的

2023-05-17 08:25 UTC, wangwenx190 commented
这个写在FramelessHelper的顶层CMakeList里不行吗，怎么每个CMakeList都要加上

2023-05-17 08:27 UTC, mentalfl0w commented
> 这个写在FramelessHelper的顶层CMakeList里不行吗，怎么每个CMakeList都要加上

是的，不可以😂，非常奇怪，我最开始的提交是放在顶层的，但是编译出来的库只有编译平台架构的内容，只有放进每一个子CMakeList里面才会正常

2023-05-17 08:29 UTC, wangwenx190 commented on CMakeLists.txt
> +option(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD "macOS only: build universal library/exemple for Mac." ON)
为什么默认是ON？

2023-05-17 08:31 UTC, mentalfl0w commented on CMakeLists.txt
> +option(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD "macOS only: build universal library/exemple for Mac." ON)
因为考虑到目前Intel架构的Mac存量还是比较客观的（我个人是用Intel的Mac办公，Apple Silicon的Mac居家使用），所以就调整为默认为ON了。

2023-05-17 08:33 UTC, wangwenx190 commented on CMakeLists.txt
> +endif()
是否输出一个警告会好些

2023-05-17 08:33 UTC, wangwenx190 commented on examples/dialog/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
这个不需要吧？

2023-05-17 08:33 UTC, wangwenx190 commented on examples/mainwindow/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
同上。

2023-05-17 08:33 UTC, wangwenx190 commented on examples/openglwidget/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
同上。

2023-05-17 08:33 UTC, wangwenx190 commented on examples/quick/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
同上。

2023-05-17 08:33 UTC, wangwenx190 commented on examples/widget/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
同上。

2023-05-17 08:33 UTC, wangwenx190 commented on src/core/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
同上。

2023-05-17 08:33 UTC, wangwenx190 commented on src/quick/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
同上。

2023-05-17 08:33 UTC, wangwenx190 commented on src/widgets/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
同上。

2023-05-17 08:33 UTC, wangwenx190 commented on CMakeLists.txt
> +option(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD "macOS only: build universal library/exemple for Mac." ON)
好的，确实比较合理。

2023-05-17 08:37 UTC, mentalfl0w commented on CMakeLists.txt
> +endif()
嗯，那这边我再加一个警告

2023-05-17 08:38 UTC, mentalfl0w commented on examples/dialog/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
这边如果不加的话，编译出来的app就不是通用架构的了，如果例子不需要通用的话应该也可以，后面我去掉example里面的

2023-05-17 08:41 UTC, wangwenx190 commented on examples/dialog/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
我指的是`set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)`这一句，没必要再重置为OFF吧？

2023-05-17 08:41 UTC, wangwenx190 commented on examples/dialog/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
例子里的还留着吧

2023-05-17 08:47 UTC, mentalfl0w commented on examples/dialog/CMakeLists.txt
> +    set(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD OFF)
> 例子里的还留着吧

是的，这个确实没必要了，我待会儿把这些都去掉

2023-05-17 09:34 UTC, wangwenx190 requested changes

2023-05-17 09:34 UTC, wangwenx190 commented on CMakeLists.txt
> +endif()
我的想法是这样的，如果不是苹果平台，并且`FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD`为ON时，输出警告，并将`FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD`重置为OFF

2023-05-17 09:36 UTC, mentalfl0w commented on CMakeLists.txt
> +endif()
> 我的想法是这样的，如果不是苹果平台，并且`FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD`为ON时，输出警告，并将`FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD`重置为OFF

是的，这样确实更合适，已修改提交

2023-05-17 09:39 UTC, wangwenx190 commented
感谢！

2023-05-17 09:50 UTC, mentalfl0w commented on CMakeLists.txt
> +option(FRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD "macOS only: build universal library/exemple for Mac." ON)
是的没错，这样更合适，已修改。

2023-05-17 10:24 UTC, mentalfl0w reviewed
完成

2023-05-17 10:38 UTC, mentalfl0w commented
编译quick的例子时，出现了一处编译错误，我顺便修复了

2023-05-17 11:36 UTC, mentalfl0w commented on CMakeLists.txt
> +include(CMakeDependentOption)
只有包含它才能使用cmake_dependent_option，才能根据APPLE来确定是ON还是OFF。APPLE是一个TRUE和FALSE的布尔量，而option只有在value是ON的时候才会认为为真，而包括TRUE、FALSE等其他值在内的其他结果都会被判定为OFF，无法实现用APPLE来决定是ON还是OFF的效果。

2023-05-17 11:52 UTC, wangwenx190 commented on CMakeLists.txt
> +include(CMakeDependentOption)
原来如此，受教了

2023-05-17 11:52 UTC, wangwenx190 commented on CMakeLists.txt
> +include(CMakeDependentOption)
这个东西是否有版本限制，目前我们最低3.20，应该是可用的吧？

2023-05-17 12:15 UTC, mentalfl0w commented on CMakeLists.txt
> +include(CMakeDependentOption)
> 这个东西是否有版本限制，目前我们最低3.20，应该是可用的吧？

没有的，这个`cmake_dependent_option`自CMake 3.0.2版本开始就有了。

2023-05-17 12:19 UTC, merged

2023-05-18 02:23 UTC, wangwenx190 commented
用GitHub Actions编译了几次，好像开启universal build之后，不能再开启LTO，不然就报错

2023-05-18 03:06 UTC, mentalfl0w commented
> 用GitHub Actions编译了几次，好像开启universal build之后，不能再开启LTO，不然就报错

我看了一下GitHub Action的编译结果，发现有为Qt 5.15.2进行编译，但Qt从Qt 5.15.9和Qt 6.2才开始支持Universal Build，我应该要加入版本判断的。我待会儿会再发起一次PR来修复一下这个Qt 5.15.2编译的问题。